repos:
- repo: local
  hooks:
  - id: clang-format
    name: clang-format
    language: system
    files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
    exclude: (json1|uint)\.c
    verbose: true
    entry: clang-format
    args: [-i,'-style={IndentWidth: 4, ColumnLimit: 100, BreakStringLiterals: false, ReflowComments: false}']
  - id: cppcheck
    name: cppcheck
    language: system
    files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
    exclude: json1\.c
    verbose: true
    entry: cppcheck
    args: [-q,--std=c++11]
  - id: black
    name: black
    language: system
    files: \.py$
    verbose: true
    entry: black
    args: [-l,'100']
  - id: flake8
    name: flake8
    language: system
    files: \.py$
    verbose: true
    entry: flake8
    args: [--max-line-length, "100", "--ignore=E501,W503,E722"]
  - id: pylint
    name: pylint
    language: system
    files: \.py$
    exclude: version\.py
    verbose: true
    entry: env PYTHONPATH=bindings/python pylint
    args: [-d, "global-statement,missing-docstring,missing-module-docstring,line-too-long,too-many-arguments,duplicate-code,redefined-outer-name,too-many-locals,bare-except,broad-except,import-outside-toplevel,protected-access,too-many-statements,too-many-branches,unspecified-encoding"]
